spring:
  application:
    name: jobinterview-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/hirereadyinterview

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 9092

eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost
      prefer-ip-address: true

rabbitmq:
  exchange:
    name: hireready.exchange
  queue:
   name: jobinterview.queue
   statusUpdateName: interview.status.queue
  routing:
    key: jobinterview.created
    statusUpdateKey: interview.status.update
